rate: 1
node_name: "vision"

basler:
  rotate_img: 180 # specify in degrees
  topic: "basler" # topic that we publish to: /node_name/topic
  camera_node: "/basler" # camera topic
  image_topic: "image_rect_color"
  publish_labelled_img: True
  has_depth: False
  run_continuous: False
  wait_for_services: True
  detect_arucos: False
  parent_frame: "vision_table_zero" # When publishing transforms, this is the base/parent frame from which they are published.

realsense:
  rotate_img: 0 # specify in degrees
  topic: "realsense" # topic that we publish to: /node_name/topic
  camera_node: "/realsense" # camera node
  image_topic: "color/camera_info"
  info_topic: "color/image_raw"
  depth_topic: "aligned_depth_to_color/image_raw"
  publish_labelled_img: True
  publish_depth_img: True
  publish_cluster_img: True
  has_depth: True
  run_continuous: False
  wait_for_services: True
  detect_arucos: False
  camera_height: 0.20 # height in meters
  parent_frame: 'panda_2/realsense' # When publishing TFs, this will be the parent frame.
  calibration_file: '/root/vision-pipeline/realsense_calib/realsense_calib.yaml'

# yolact config
obj_detection:
  yolact_dataset_file: data_limited/yolact/real_from_synthetic_2021-07-07/dataset.json
  yolact_score_threshold: 0.55